package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"eztrip/api-go/graph/model"
	"eztrip/api-go/trip"
	"eztrip/api-go/user"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*user.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*user.User, error) {
	return r.UserResolver.CurrentUser(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*user.User, error) {
	return r.UserResolver.Users(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*user.User, error) {
	return r.UserResolver.User(ctx, id)
}

// TripSuggestion is the resolver for the tripSuggestion field.
func (r *queryResolver) TripSuggestion(ctx context.Context, prompt string) (string, error) {
	return r.TripResolver.TripSuggestion(ctx, prompt)
}

// ID is the resolver for the id field.
func (r *tripResolver) ID(ctx context.Context, obj *trip.Trip) (string, error) {
	return obj.ID.String(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Trip returns TripResolver implementation.
func (r *Resolver) Trip() TripResolver { return &tripResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tripResolver struct{ *Resolver }
